// Template definitions for the Project Spawner UI

export interface SpawnTemplate {
  id: string;
  name: string;
  type: "rust_lib" | "rust_bin" | "typescript" | "python" | "ios" | "web";
  icon: string;
  description: string;
  language: string;
  example: string;
  includes: string[];
}

export interface SpawnPhase {
  id: string;
  label: string;
  description: string;
}

export const spawnTemplates: SpawnTemplate[] = [
  {
    id: "rust-lib",
    name: "Rust Library",
    type: "rust_lib",
    icon: "Library",
    description: "A Rust library crate with Cargo.toml, src/lib.rs, and test scaffolding",
    language: "Rust",
    example: "cc-graph-kernel",
    includes: ["Cargo.toml", "src/lib.rs", "tests/integration.rs", ".gitignore", "README.md"],
  },
  {
    id: "rust-bin",
    name: "Rust Binary",
    type: "rust_bin",
    icon: "Terminal",
    description: "A Rust CLI binary with clap argument parsing and tokio async runtime",
    language: "Rust",
    example: "cc-retrieval-indexer",
    includes: ["Cargo.toml", "src/main.rs", "src/cli.rs", ".gitignore", "README.md"],
  },
  {
    id: "typescript",
    name: "TypeScript Package",
    type: "typescript",
    icon: "Braces",
    description: "An npm package with TypeScript, Jest testing, and ESLint config",
    language: "TypeScript",
    example: "cc-cognitive-pulse",
    includes: ["package.json", "tsconfig.json", "src/index.ts", "tests/index.test.ts", ".gitignore"],
  },
  {
    id: "python",
    name: "Python Package",
    type: "python",
    icon: "Code2",
    description: "A Python project with pyproject.toml, pytest, and virtual environment setup",
    language: "Python",
    example: "cc-vision-mesh",
    includes: ["pyproject.toml", "src/__init__.py", "tests/test_main.py", ".gitignore", "README.md"],
  },
  {
    id: "ios",
    name: "iOS App",
    type: "ios",
    icon: "Smartphone",
    description: "A SwiftUI iOS app with Assets.xcassets, Info.plist, and the zero-retry pipeline config",
    language: "Swift",
    example: "SecuriClaw",
    includes: ["project.yml", "App.swift", "ContentView.swift", "Assets.xcassets", "Info.plist", "ExportOptions.plist"],
  },
  {
    id: "web",
    name: "Web App",
    type: "web",
    icon: "Globe",
    description: "A Next.js 14 web app with Tailwind CSS, TypeScript, and deployment config",
    language: "TypeScript",
    example: "diomande-automation",
    includes: ["package.json", "next.config.ts", "tailwind.config.ts", "src/app/page.tsx", "src/app/layout.tsx"],
  },
];

export const spawnPhases: SpawnPhase[] = [
  { id: "proposed", label: "Proposed", description: "Request submitted and queued" },
  { id: "registered", label: "Registered", description: "Project registered in system" },
  { id: "scaffolded", label: "Scaffolded", description: "Directory structure created" },
  { id: "git-init", label: "Git Init", description: "Repository initialized" },
  { id: "code-gen", label: "Code Gen", description: "Initial code generated by AI" },
  { id: "active", label: "Active", description: "Project is live and building" },
  { id: "complete", label: "Complete", description: "Spawning process finished" },
];

export const spawnCategories = [
  "apps",
  "infrastructure",
  "agents",
  "tools",
  "creative",
  "research",
] as const;

export type SpawnCategory = (typeof spawnCategories)[number];
